import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "../components/SessionProvider";
import SideNavMenu from "@/components/SideNavMenu";
import TopUserBar from "@/components/TopUserBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <div className="flex h-full">
            <SideNavMenu />
            <div className="flex flex-col flex-1 h-full">
              <TopUserBar />
              <main className="flex-1">{children}</main>
            </div>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
