import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import SideNavMenu from "@/components/side-nav/SideNavMenu";
import TopUserBar from "@/components/top-bar/TopUserBar";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <div className="flex h-full">
            <SideNavMenu />
            <div className="flex flex-col flex-1 h-full">
              <TopUserBar session={session} />
              <main className="flex-1">{children}</main>
              <Toaster />
            </div>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
